#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Orchis-Dark-Compact'
ICONS='Qogir-dark'
FONT='FiraCode Nerd Font 16'


SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	#${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
